name: Snyk Vulnerability Analysis

on:
  push:
    branches:
      - main

jobs:
  analyze-snyk-vulnerabilities:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Read and Extract Snyk Vulnerabilities
      run: |
        JSON_FILE_PATH="$(pwd)/bom-result.json"

        # Print the content of the JSON file
        # echo "Contents of $JSON_FILE_PATH:"
        # cat "$JSON_FILE_PATH"

        # Extract the key containing vulnerability values
        VULNERABILITY_KEY=$(jq -r '.data.vulnerabilities' "$JSON_FILE_PATH")
        echo "Contents of $VULNERABILITY_KEY"

        # Check if the key exists and is not null
        if [ "$VULNERABILITY_KEY" != "null" ]; then
          echo "Extracted Vulnerabilities: $VULNERABILITY_KEY"
        else
          echo "No vulnerabilities found or key is null."
        fi
