name: Snyk Vulnerability Analysis

on:
  push:
    branches:
      - main

jobs:
  analyze-snyk-vulnerabilities:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Read and Extract Snyk Vulnerabilities
      run: |
        JSON_FILE_PATH="$(pwd)/bom-result.json"

        # Print the content of the JSON file
        echo "Contents of $JSON_FILE_PATH:"
        cat "$JSON_FILE_PATH"

        # Extract the key containing vulnerability values
        VULNERABILITY_KEY=$(jq -r '.data.attributes.vulnerabilities_by_severity' "$JSON_FILE_PATH")

        # Print the extracted value
        echo "Extracted Vulnerabilities: $VULNERABILITY_KEY"
